<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ../glb/Suit_Female.glb --transform --types --suspense
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group } from "three";
  import {
    T,
    type Props,
    type Events,
    type Slots,
    forwardEventHandlers,
  } from "@threlte/core";
  import { useGltf, useGltfAnimations, useSuspense } from "@threlte/extras";

  type $$Props = Props<THREE.Group>;
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();

  const suspend = useSuspense();

  type ActionName =
    | "Death"
    | "Defeat"
    | "Idle"
    | "Jump"
    | "PickUp"
    | "Punch"
    | "RecieveHit"
    | "Roll"
    | "Run"
    | "Run_Carry"
    | "Shoot_OneHanded"
    | "SitDown"
    | "StandUp"
    | "SwordSlash"
    | "Victory"
    | "Walk"
    | "Walk_Carry";
  type GLTFResult = {
    nodes: {
      Cube004: THREE.SkinnedMesh;
      Cube004_1: THREE.SkinnedMesh;
      Cube004_2: THREE.SkinnedMesh;
      Cube004_3: THREE.SkinnedMesh;
      Cube004_4: THREE.SkinnedMesh;
      Cube004_5: THREE.SkinnedMesh;
      Cube004_6: THREE.SkinnedMesh;
      Bone: THREE.Bone;
    };
    materials: {
      Skin: THREE.MeshStandardMaterial;
      Black: THREE.MeshStandardMaterial;
      Belt: THREE.MeshStandardMaterial;
      Shirt: THREE.MeshStandardMaterial;
      Details: THREE.MeshStandardMaterial;
      Face: THREE.MeshStandardMaterial;
      Hair: THREE.MeshStandardMaterial;
    };
  };

  const gltf = suspend(
    useGltf<GLTFResult>("/gltf/Suit_Female-transformed.glb", { useDraco: true })
  );
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

  export let nextAction = "Idle";
  export let prevAction = ""; 
  $: $actions[prevAction]?.stop();
  $: $actions[nextAction]?.play();

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="CharacterArmature">
        <T is={gltf.nodes.Bone} />
        <T.Group name="Body_1">
          <T.SkinnedMesh
            name="Cube004"
            geometry={gltf.nodes.Cube004.geometry}
            material={gltf.materials.Skin}
            skeleton={gltf.nodes.Cube004.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_1"
            geometry={gltf.nodes.Cube004_1.geometry}
            material={gltf.materials.Black}
            skeleton={gltf.nodes.Cube004_1.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_2"
            geometry={gltf.nodes.Cube004_2.geometry}
            material={gltf.materials.Belt}
            skeleton={gltf.nodes.Cube004_2.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_3"
            geometry={gltf.nodes.Cube004_3.geometry}
            material={gltf.materials.Shirt}
            skeleton={gltf.nodes.Cube004_3.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_4"
            geometry={gltf.nodes.Cube004_4.geometry}
            material={gltf.materials.Details}
            skeleton={gltf.nodes.Cube004_4.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_5"
            geometry={gltf.nodes.Cube004_5.geometry}
            material={gltf.materials.Face}
            skeleton={gltf.nodes.Cube004_5.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_6"
            geometry={gltf.nodes.Cube004_6.geometry}
            material={gltf.materials.Hair}
            skeleton={gltf.nodes.Cube004_6.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
